export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOAD_BLOGS="LOAD_BLOGS";
export const REMOVE_BLOG="REMOVE_BLOG";
export const GET_BLOG="GET_BLOG";
export const GET_RESPONSES="GET_RESPONSES";
export const DELETE_RESPONSE="DELETE_RESPONSE";
export const POST_RESPONSE="POST_RESPONSE";


